/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TicketStatusService } from "../ticketStatus.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TicketStatusCreateInput } from "./TicketStatusCreateInput";
import { TicketStatus } from "./TicketStatus";
import { TicketStatusFindManyArgs } from "./TicketStatusFindManyArgs";
import { TicketStatusWhereUniqueInput } from "./TicketStatusWhereUniqueInput";
import { TicketStatusUpdateInput } from "./TicketStatusUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TicketStatusControllerBase {
  constructor(
    protected readonly service: TicketStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TicketStatus })
  @nestAccessControl.UseRoles({
    resource: "TicketStatus",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTicketStatus(
    @common.Body() data: TicketStatusCreateInput
  ): Promise<TicketStatus> {
    return await this.service.createTicketStatus({
      data: {
        ...data,

        tickets: data.tickets
          ? {
              connect: data.tickets,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        tickets: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TicketStatus] })
  @ApiNestedQuery(TicketStatusFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TicketStatus",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketStatuses(
    @common.Req() request: Request
  ): Promise<TicketStatus[]> {
    const args = plainToClass(TicketStatusFindManyArgs, request.query);
    return this.service.ticketStatuses({
      ...args,
      select: {
        createdAt: true,
        id: true,

        tickets: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TicketStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketStatus",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketStatus(
    @common.Param() params: TicketStatusWhereUniqueInput
  ): Promise<TicketStatus | null> {
    const result = await this.service.ticketStatus({
      where: params,
      select: {
        createdAt: true,
        id: true,

        tickets: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TicketStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketStatus",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTicketStatus(
    @common.Param() params: TicketStatusWhereUniqueInput,
    @common.Body() data: TicketStatusUpdateInput
  ): Promise<TicketStatus | null> {
    try {
      return await this.service.updateTicketStatus({
        where: params,
        data: {
          ...data,

          tickets: data.tickets
            ? {
                connect: data.tickets,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          tickets: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TicketStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketStatus",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTicketStatus(
    @common.Param() params: TicketStatusWhereUniqueInput
  ): Promise<TicketStatus | null> {
    try {
      return await this.service.deleteTicketStatus({
        where: params,
        select: {
          createdAt: true,
          id: true,

          tickets: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
